### ISSUE TITLE
Request not to mandate same names for assisted parameters

### ISSUE THREAD

**Issue by Ethan1983** [square/AssistedInject#81]
Request not to mandate same names for assisted parameters. In my case, changing params to workerParameters fixed it but would be nice not to force same names.

InternalWorkerFactory.java:9: error: Factory method parameters do not match constructor @Assisted parameters.
    public abstract T create(@org.jetbrains.annotations.NotNull()
                      ^
  Missing:
   * androidx.work.WorkerParameters params
  Unknown:
   * androidx.work.WorkerParameters workerParameters

**Comment by JakeWharton** [comment]
I'd like to make it so that name matching is only required when duplicate bindings exist but haven't done so yet

**Comment by Ethan1983** [comment]
Sounds good, thanks.

**Comment by gpeal** [comment]
@JakeWharton AssistedInject also fails if you use an interface for your `@AssistedInject.Factory` if it extends an interface that is in another module.

For example: [this](https://github.com/chrisbanes/tivi/pull/254/files#diff-cc68ee10af05fcf82f1d0f2932918243R52) will fail if ChildWorkerFactory is in a different module.

**Comment by JakeWharton** [comment]
This isn't a high priority for me so PRs welcome.

Not sure how to deal with the interface in another module case when you
have two assisted parameters of the same type. If you don't compile with
parameters embedded in the bytecode then you're out of luck (unless we
revert to qualifier semantics like we original did).

**Comment by jaychang0917** [comment]
This also fails if the parameter type is generic.

```kotlin
interface Command {
  interface Factory {
    fun <T1 : Any> create(p1: T1) : Command
  }
}
```

It would be handful if I have a set of generic factory methods. Currently I hand-write the factory like this:
```kotlin
interface Command {
  interface Factory {
    fun <T1 : Any> create(number: T1) : Command
  }
}

class FooCommand (private val foo: String) : Command {
  fun foo() {
    println("foo $foo")
  }

  interface Factory : Command.Factory
}

class FooCommandFactory : FooCommand.Factory {
  override fun <T1 : Any> create(number: T1): Command {
    return FooCommand(number as String)
  }
}

class BarCommand (private val bar: Int) : Command {
  fun bar() {
    println("bar $bar")
  }

  interface Factory : Command.Factory
}

class BarCommandFactory : BarCommand.Factory {
  override fun <T1 : Any> create(number: T1): Command {
    return BarCommand(number as Int)
  }
}

fun main(vararg args: String) {
  (FooCommandFactory().create("foo") as FooCommand).foo()
  (BarCommandFactory().create(123) as BarCommand).bar()
}
```

**Comment by JakeWharton** [comment]
Not seeing how that's related unless you're just adding another example of
a factory interface in a library compiled without parameter names enabled.

**Comment by jaychang0917** [comment]
> Not seeing how that's related unless you're just adding another example of a factory interface in a library compiled without parameter names enabled.

The `Command.Factory` interface and `FooCommand` are in the same file, but the compiler will throw the error saying the parameter types are not matching even using the same parameter name.

```
interface Command {
    interface Factory {
        fun <T1 : Any> create(arg1: T1) : Command
    }
}

class FooCommand @AssistedInject constructor(
    @Assisted private val arg1: String
) : Command {
    @AssistedInject.Factory
    interface Factory : Command.Factory
}
```

```
Factory method parameters do not match constructor @Assisted parameters.
        public abstract <T1 extends java.lang.Object>Command create(@org.jetbrains.annotations.NotNull()
                                                                 ^
  Missing:
   * java.lang.String arg1
  Unknown:
   * T1 arg1
```

**Comment by JakeWharton** [comment]
That isn't related to this issue because it's related to types, not names. As far as I can tell it's working as intended since nothing forces you to use the right type there.

**Comment by nlgtuankiet** [comment]
I'm facing the same issue with @gpeal, the only way to work around this is copy paste interface method for every factory :(

```
e: TasksBindingModule.java:9: error: cannot find symbol
    TasksViewModel.Factory bind(TasksViewModel_AssistedFactory factory);
                                ^
  symbol:   class TasksViewModel_AssistedFactory
  location: interface TasksBindingModule
e: error: Factory method parameters do not match constructor @Assisted parameters.
  Missing:
   * com.sample.todo.tasks.TasksState initialState
  Unknown:
   * com.sample.todo.tasks.TasksState arg0
```

**Comment by semanticer** [comment]
I have the same problem as you @nlgtuankiet and @gpeal and I'm trying to solve it with copypasting solution (copy of WorkerFactory class AND the interface for every module) but I'm getting errors because dagger is trying to initialize workers with the wrong Factory objects. Can you share any details on your workarounds? This is a big pain in the ass, thanks for any help.

**Comment by davidliu** [comment]
Looks like there's a confounding issue with kotlin 1.3.50, where if you have a factory extending another interface, the parameter name isn't read correctly the first time. For example:

```
class Thingy
@AssistedInject
constructor(@Assisted val foo: String, val bar: Long) {
    @AssistedInject.Factory
    interface Factory : TheFactory<Thingy>
}

interface TheFactory<T : Any> {
    fun create(foo: String): T
}
```

Results in:

```
e: /AssistedInject/assisted-inject-sample-android/build/tmp/kapt3/stubs/debug/com/example/Thingy.java:46: error: Factory method parameters do not match constructor @Assisted parameters. Both parameter type and name must match.
    public Thingy(@org.jetbrains.annotations.NotNull()
           ^
  Declared by constructor, unmatched in factory method:
   * java.lang.String foo
  Declared by factory method, unmatched in constructor:
   * java.lang.String arg0
```

It works correctly on kotlin 1.3.42.

**Comment by davidliu** [comment]
Any chance I can get #121 looked at as a potential solution for this issue?

**Comment by JakeWharton** [comment]
It's on my queue

**Comment by micHar** [comment]
For anyone having the same issue as @davidliu on Kotlin 1.3.50 - you just need to clean and rebuild.

**Comment by davidliu** [comment]
@micHar as a temporary stopgap, you can also try it with my PR applied.

```
    compileOnly 'com.github.davidliu.AssistedInject:assisted-inject-annotations-dagger2:78f23af7'
    kapt 'com.github.davidliu.AssistedInject:assisted-inject-processor-dagger2:78f23af7'
```

It's been working well for my usages on 1.3.50, though let me know if you run into any issues.

**Comment by jkaan** [comment]
@davidliu Out of curiosity, you're just renaming the parameter name if the type matches if there is only one parameter in the constructor of the class, right?

While fixing the issue, doesn't that also hide the fact that something else is actually broken?

**Comment by davidliu** [comment]
@jkaan No, I haven't dug into that one, as it hasn't been an issue with the PR applied. I'll recheck if it still bugs on 1.3.60 next week. Thinking back, it might have been an incremental kapt issue; I've been having other issues with incremental kapt dropping needed information.

**Comment by davidliu** [comment]
@jkaan Hmm, I'm unable to repro it any more, so it might have been something flaky on my end? It's been a long time though, so I don't remember all the details.

**Comment by jkaan** [comment]
@davidliu I've just tried it as well and seems like also on my end it doesn't happen anymore. I've added a workaround to our code to fix the issue but I'll remove that and post here again if I see it again :). Thanks for checking!

**Comment by NitroG42** [comment]
I'm still having this issue with assistedInject 0.5.2, kotlin 1.3.61 and workmanager 2.3.0-rc01. Tried to clean build and renaming to arg0 and arg1 worked (yikes...)
No clue why is that, I'm using android gradle plugin 4.0.0-alpha08 so that might be the cause ?

**Comment by james-airspace** [comment]
@NitroG42 I was having this same issue, and I read @davidliu 's comment above:
https://github.com/square/AssistedInject/issues/81#issuecomment-570695054

Disabling incremental kapt worked for me.

**Comment by GuilhE** [comment]
Have the same problem but only in a multi module project where, in this case, the ViewModelAssistedFactory is inside _module-core_ and the viewmodel using it is in the _app module._

```
    @AssistedInject.Factory
    interface Factory : ViewModelAssistedFactory<MyViewModel>
```

`kotlin_gradle_plugin`: 1.3.61
`google_dagger`: 2.26
`assisted_inject_annotations_dagger2`: 0.5.2
`assisted_inject_processor_dagger2`: 0.5.2

Adding `kotlin.incremental=false` in `gradle.properties` didn't help.

**Comment by matiasdelbel** [comment]
@gpeal 
> @JakeWharton AssistedInject also fails if you use an interface for your `@AssistedInject.Factory` if it extends an interface that is in another module.
> 
> For example: [this](https://github.com/chrisbanes/tivi/pull/254/files#diff-cc68ee10af05fcf82f1d0f2932918243R52) will fail if ChildWorkerFactory is in a different module.

In this case, could you do this as a workaround? Creating an interface that overrides the interface in the library...

```
internal interface AppViewModelFactory<T : ViewModel> : ViewModelFactory<T> {

    override fun create(handle: SavedStateHandle): T
}```
